import {
  buildExpectedKeyPoints,
  buildReferenceSampleAnswer,
  type Difficulty,
} from './question-reference';
import type { QuestionSeed } from './question-types';

/**
 * Thirty common JS interview pillars (execution → browser), tagged interview-core for filtering.
 */
export function buildJavaScriptInterviewCoreSeeds(): QuestionSeed[] {
  const conceptual = 'conceptual' as const;

  function seed(
    idSuffix: string,
    category: string,
    topic: string,
    question: string,
    hint: string,
    difficulty: Difficulty = 'medium',
  ): QuestionSeed {
    return {
      id: `js-interview-core-${idSuffix}`,
      stack: 'javascript',
      tech_stack: 'javascript',
      difficulty,
      question_type: conceptual,
      category,
      topic,
      question,
      expected_key_points: buildExpectedKeyPoints('javascript', topic, difficulty, conceptual),
      hint,
      coding_template: null,
      coding_test_cases: null,
      sample_answer: buildReferenceSampleAnswer('javascript', topic, difficulty, conceptual),
      tags: ['javascript', 'interview-core', idSuffix],
      is_active: true,
    };
  }

  return [
    seed(
      'exec-context-call-stack',
      'Execution, Scope & Memory',
      'execution context & call stack',
      'Explain execution context and the call stack in JavaScript. What happens when a function is invoked?',
      'Think global vs function context and how frames push/pop.',
      'easy',
    ),
    seed(
      'var-let-const-tdz',
      'Execution, Scope & Memory',
      'var, let, const — scope, hoisting, TDZ',
      'Compare var, let, and const in terms of scope, hoisting, and the temporal dead zone.',
      'Mention block scope, function scope, redeclaration, and when bindings are uninitialized.',
      'easy',
    ),
    seed(
      'lexical-scope-chain',
      'Execution, Scope & Memory',
      'lexical scope & scope chain',
      'What is lexical scope, and how does the scope chain resolve identifiers at runtime?',
      'Link lexical environment to where code is written, not where it runs.',
      'medium',
    ),
    seed(
      'closures-behavior',
      'Execution, Scope & Memory',
      'closures — behavior',
      'Explain closures by describing behavior: what persists after a function returns, and why that matters.',
      'Give a practical example (e.g., counters, callbacks, modules), not only a textbook definition.',
      'medium',
    ),
    seed(
      'shadowing-illegal-shadowing',
      'Execution, Scope & Memory',
      'shadowing & illegal shadowing',
      'What is variable shadowing in nested scopes? What is illegal shadowing with let/const in JavaScript?',
      'Contrast valid shadowing vs cases that throw SyntaxError.',
      'medium',
    ),
    seed(
      'gc-memory-leaks',
      'Execution, Scope & Memory',
      'garbage collection & memory leaks',
      'Describe garbage collection at a high level in JS engines. What patterns commonly cause memory leaks?',
      'Mention retained DOM refs, closures holding large graphs, timers/listeners.',
      'medium',
    ),

    seed(
      'fn-declaration-vs-expression',
      'Functions & this',
      'function declarations vs expressions',
      'What is the difference between function declarations and function expressions (including hoisting)?',
      'Cover anonymous vs named function expressions where relevant.',
      'easy',
    ),
    seed(
      'this-binding-rules',
      'Functions & this',
      'this binding — default, implicit, explicit, new',
      'Explain how this is bound in JavaScript: default, implicit, explicit (call/apply/bind), and new.',
      'Walk through one short example per rule.',
      'medium',
    ),
    seed(
      'call-apply-bind',
      'Functions & this',
      'call, apply, bind',
      'Compare Function.prototype.call, apply, and bind: signatures, use cases, and what each returns.',
      'Note immediate invocation vs returning a bound function.',
      'medium',
    ),
    seed(
      'arrow-vs-regular-functions',
      'Functions & this',
      'arrow functions vs regular functions',
      'How do arrow functions differ from regular functions regarding this, arguments, constructors, and prototypes?',
      'Mention when you would avoid arrow functions.',
      'medium',
    ),
    seed(
      'currying-partial-application',
      'Functions & this',
      'currying & partial application',
      'What is currying versus partial application? Show how either appears in everyday JS APIs.',
      'Keep it practical—logging wrappers, fetch configurators, etc.',
      'medium',
    ),
    seed(
      'higher-order-functions',
      'Functions & this',
      'higher-order functions',
      'What is a higher-order function? Give examples from the standard library or frameworks.',
      'map/filter/reduce are fair game; relate to reusability and composition.',
      'easy',
    ),

    seed(
      'event-loop-microtasks-macrotasks',
      'Async JavaScript',
      'event loop — call stack, microtasks, task queue',
      'Explain the JavaScript event loop: call stack, macrotasks (tasks), and microtasks.',
      'Include where Promises queue relative to setTimeout.',
      'medium',
    ),
    seed(
      'promises-chaining',
      'Async JavaScript',
      'promises & chaining',
      'How do Promises work, and how does then/catch chaining propagate errors and values?',
      'Mention fulfillment vs rejection and returning Promises from handlers.',
      'medium',
    ),
    seed(
      'async-await-errors',
      'Async JavaScript',
      'async / await — errors & sequencing',
      'How do async/await relate to Promises? How do you handle errors and enforce sequencing?',
      'Compare try/catch with .catch() chains.',
      'medium',
    ),
    seed(
      'race-stale-closures',
      'Async JavaScript',
      'race conditions & stale closures',
      'Give examples of race conditions or stale closures in async UI code and how you mitigate them.',
      'Think aborted requests, stale state in hooks/effects, counters/tokens.',
      'hard',
    ),
    seed(
      'timers-vs-microtasks',
      'Async JavaScript',
      'timers vs microtasks',
      'Contrast setTimeout/setInterval scheduling with microtasks (e.g., queueMicrotask, Promise callbacks).',
      'Predict relative ordering in a short snippet mindset.',
      'medium',
    ),
    seed(
      'promise-static-methods',
      'Async JavaScript',
      'Promise utilities — all, allSettled, race, any',
      'Explain Promise.all, Promise.allSettled, Promise.race, and Promise.any: semantics and failure behavior.',
      'Mention AggregateError where relevant.',
      'medium',
    ),

    seed(
      'equality-truthy-falsy',
      'Data, References & ES6+',
      '== vs === & truthy/falsy',
      'Compare == and === in JavaScript. What are common falsy values, and what surprises do truthy checks hide?',
      'Mention coercion briefly for ==.',
      'easy',
    ),
    seed(
      'reference-mutation',
      'Data, References & ES6+',
      'object & array reference behavior',
      'How does reference assignment work for objects and arrays? What is the difference versus copying?',
      'Relate to bugs in React state or shared config objects.',
      'easy',
    ),
    seed(
      'deep-vs-shallow-copy',
      'Data, References & ES6+',
      'deep vs shallow copy',
      'What is shallow vs deep copying in JavaScript? Name common APIs and their limitations.',
      'structuredClone, JSON, spread — trade-offs.',
      'medium',
    ),
    seed(
      'destructure-rest-spread',
      'Data, References & ES6+',
      'destructuring, rest & spread',
      'Explain destructuring assignment, rest parameters, and spread: how they differ and typical use cases.',
      'Show object vs array patterns in one sentence each.',
      'easy',
    ),
    seed(
      'map-set-weak-collections',
      'Data, References & ES6+',
      'Map, Set, WeakMap, WeakSet',
      'Why do Map, Set, WeakMap, and WeakSet exist alongside plain objects? When would you choose each?',
      'Mention keys, iteration, and weak collection garbage-collection behavior.',
      'medium',
    ),

    seed(
      'event-phases',
      'Browser & Runtime Fundamentals',
      'event bubbling, capturing, target phase',
      'Describe the three DOM event phases: capture, target, and bubble.',
      'Mention addEventListener options { capture }.',
      'easy',
    ),
    seed(
      'event-delegation',
      'Browser & Runtime Fundamentals',
      'event delegation',
      'What is event delegation, why does it work, and when does it fail or become awkward?',
      'Dynamic lists, stopPropagation, focus events — briefly.',
      'medium',
    ),
    seed(
      'prevent-default-stop-propagation',
      'Browser & Runtime Fundamentals',
      'preventDefault vs stopPropagation',
      'What is the difference between preventDefault() and stopPropagation() on DOM events?',
      'Give one example where only one of them is appropriate.',
      'easy',
    ),
    seed(
      'dom-vs-virtual-dom',
      'Browser & Runtime Fundamentals',
      'DOM vs virtual DOM',
      'What is the conceptual difference between the real DOM and a virtual DOM as used by libraries like React?',
      'Stay high-level: reconciliation, batching—not framework marketing.',
      'medium',
    ),
    seed(
      'reflow-repaint',
      'Browser & Runtime Fundamentals',
      'reflow vs repaint',
      'What are reflow (layout) and repaint in the browser? What kinds of changes trigger each?',
      'Mention reading layout properties after writes.',
      'medium',
    ),
    seed(
      'web-storage-cookies',
      'Browser & Runtime Fundamentals',
      'web storage — localStorage, sessionStorage, cookies',
      'Compare localStorage, sessionStorage, and cookies: scope, lifetime, size, and sending to the server.',
      'Mention HttpOnly cookies for sensitive tokens.',
      'medium',
    ),
    seed(
      'polyfills-feasibility',
      'Browser & Runtime Fundamentals',
      'polyfills — what can and cannot be polyfilled',
      'What kinds of JavaScript or web platform features can be polyfilled, and which cannot—why?',
      'Think syntax vs runtime APIs vs engine-level behavior.',
      'hard',
    ),
  ];
}
